### ISSUE TITLE
What are the OSS license terms?

### ISSUE THREAD

**Issue by muniu** [kamochu/pardus#5]
Hi Samuel,

I stumbled upon your project the other day, and whilst building something similar in java, it helped me make the move to php. What are the license terms if I were to use this in a commercial environment?

**Comment by kamochu** [comment]
Hi Muniu. I have not finalized on the licensing model of the project. The version on Github is not upto date. What are you at? Are you running your own PRS business or developing a solution for someone?

**Comment by muniu** [comment]
I'm an independent ISV and as such always on the lookout for interesting projects. Yours was of particular interest as I has a while back played with the SDP via java (axis2) and didn't have a pleasant experience.
I don't think I shall be running my own PRS business anytime soon(currently happy with the great service I get from Africastalking;unless I get a better alternative) but good to see and learn from others.

**Comment by kamochu** [comment]
Cool bro! I started the project for fun :-). I used to work for Safaricom and I realized many PRSPs have challenges integrating to SDP and based on the little knowledge i have i decided to start a small project.

If you know techie who you think can benefit from this project, please share with them.

My ultimate goal is to promote collaboration and code sharing in Kenya. I believe there is something we can learn from one another and together we can do greater things.

**Comment by muniu** [comment]
Most definitely Kamochu! I'll fork, do a walkthrough and maybe a few pull requests later.

**Comment by kamochu** [comment]
:+1:
